// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Layouts/Aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./src/components/Layouts/Header.vue')['default']
    ItemContent: typeof import('./src/components/Menu/ItemContent.vue')['default']
    Layouts: typeof import('./src/components/Layouts/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    RenderMenu: typeof import('./src/components/Menu/RenderMenu.vue')['default']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
  }
}

export {}
